### PR TITLE
Enables new tabs to open on same cwd, fixes #14

### LINKED ISSUE #14: Shell Prompt breaks "New tabs open" osx feature
Opening a new Terminal Tab, or Window in OSX can be configured to start in CWD or HOME:

osx terminal startup configuration

Using the "Shell Prompt" script will break that functionality and new Tabs and Windows will always open at HOME.

### PR DESCRIPTION
**Pull request by thanpolas**

### CODE REVIEW

**Comment by jesperronn** [comment]
:+1: this has burnt me and is highly annoying when I open a new console 

(yes, @cowboy, of course, it's *your* call, *your* dotfiles) :-)

**Comment by cowboy** [comment]
I still don't see an `update_terminal_cwd` command in my path. Where does it exist?

**Comment by jesperronn** [comment]
I have it defined as a function on my macbook (Yosemite 10.10.1):

```
[20:51:09] $ type -t update_terminal_cwd
function
$
````

**Comment by mathiasbynens** [comment]
You all know iTerm2 has a built-in thing for this, right?

Preferences → Profiles → General → Working Directory → Reuse previous session’s directory

**Comment by cowboy** [comment]
@jesperronn I'm on 10.8.5 still, and `update_terminal_cwd` doesn't exist.

Thanks, @mathiasbynens, let's use that instead!

**Comment by jesperronn** [comment]
@mathiasbynens the same setting is in the standard Mac Terminal.app as well. @cowboy for the record I decided to merge this PR into my own fork which fixed the behaviour (new tabs open in in cwd).

If I don't use the PR here, my terminal will always open in HOME dir regardless on the setting in Mac Terminal.app: 
https://camo.githubusercontent.com/dfc77fcc56aab4d718ce2a3800210129072ffeb3/687474703a2f2f7468616e2e706f6c2e61732f4e78596b2f53637265656e25323053686f74253230323031332d30342d30312532306174253230332e30392e3337253230504d2e706e67

I understand you will not merge since if the `update_terminal_cwd` is missing on 10.8.5.

So, for the record, there must be some settings in these .dotfiles which override standard behaviour. Any idea what that could be?

**Comment by cowboy** [comment]
I use [iTerm 2](https://github.com/cowboy/dotfiles/blob/e6a288fd83737df6eebd116c2a5946f1afa20b9f/init/30_osx_homebrew_casks.sh#L34) instead of Terminal.app and highly recommend that everyone else do the same. I'm not sure what the problem might be!

**Pull request closed without merging**
